version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - ES_URLS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    command: ./api

  migration:
    build: .
    environment:
      - ES_URLS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    command: sh -c "./wait-for.sh elasticsearch:9200 -- ./migrate"
    volumes:
      - ./data:/app/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
