definitions:
  response.PaginationMeta:
    properties:
      current_page:
        type: integer
      page_size:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
  response.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      pagination:
        $ref: '#/definitions/response.PaginationMeta'
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: Product Service API with Elasticsearch.
  title: Product Service API
  version: "1.0"
paths:
  /api/v1/products/search:
    get:
      consumes:
      - application/json
      description: Search products with pagination
      parameters:
      - description: Search query (optional)
        in: query
        name: q
        type: string
      - description: 'Page number (default: 1)'
        in: query
        name: page
        type: integer
      - description: 'Page size (default: 10)'
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Search products
      tags:
      - Products
swagger: "2.0"
